# Generated by Django 3.2.3 on 2022-05-01 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fooditem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Class', models.CharField(max_length=50)),
                ('Type', models.CharField(max_length=50)),
                ('Group', models.CharField(max_length=50)),
                ('Food', models.CharField(max_length=50)),
                ('Allergy', models.CharField(max_length=50)),
            ],
        ),
    ]
